### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by infinite-Joy** [rodrigosetti/recruitr#1]
Documentation on the project is quite minimal. It would be great if there could be some build documentation. Currently I am having issues with having a local build in my machine. The error is shown below. I am sure this is a very trivial error and can be easily fixed for first time builds.

    django.db.utils.OperationalError: no such table: coding_problems_codingproblem [09/Jul/2017 19:14:25] "GET /challenges/ HTTP/1.1" 500 186698

**Comment by sourabhtk37** [comment]
One has to individually make the migrations of the apps (currently two `candidates` and `coding_problems`)
`./manage.py makemigrations coding_platforms candidates`

This will create migrations for each app. Then simply `./manage.py migrate` will create the tables in sqlite DB.

**Comment by sourabhtk37** [comment]
I have added some setup docs over at my fork. Feel free to look at it. @infinite-Joy 
[here](https://github.com/hackions/recruitr/blob/master/docs/install_instructions.md)

**Comment by rodrigosetti** [comment]
Thanks @sourabhtk37 . Please open a PR :)
